export function SpecialCharactersEmoji( editor ) {
    editor.plugins.get( 'SpecialCharacters' ).addItems( 'Emoji',
        [
            { title: 'face 1', character: '😀' },
            { title: 'face 2', character: '😃' },
            { title: 'face 3', character: '😄' },
            { title: 'face 4', character: '😁' },
            { title: 'face 5', character: '😆' },
            { title: 'face 6', character: '😅' },

            { title: 'face 7', character: '😂' },
            { title: 'face 8', character: '🤣' },
            { title: 'face 10', character: '😊' },
            { title: 'face 11', character: '😇' },
            { title: 'face 12', character: '🙂' },
            { title: 'face 13', character: '🙃' },
            { title: 'face 14', character: '😉' },
            { title: 'face 15', character: '😌' },
            { title: 'face 16', character: '😍' },
            { title: 'face 17', character: '🥰' },
            { title: 'face 18', character: '😘' },
            { title: 'face 19', character: '😗' },
            { title: 'face 20', character: '😙' },
            { title: 'face 21', character: '😚' },
            { title: 'face 22', character: '😋' },
            { title: 'face 23', character: '😛' },
            { title: 'face 24', character: '😝' },
            { title: 'face 25', character: '😜' },
            { title: 'face 26', character: '🤪' },
            { title: 'face 27', character: '🤨' },
            { title: 'face 28', character: '🧐' },
            { title: 'face 29', character: '🤓' },
            { title: 'face 30', character: '😎' },
            { title: 'face 31', character: '🤩' },
            { title: 'face 32', character: '🥳' },
            { title: 'face 33', character: '😏' },
            { title: 'face 34', character: '😒' },
            { title: 'face 35', character: '😞' },
            { title: 'face 36', character: '😔' },
            { title: 'face 37', character: '😟' },
            { title: 'face 38', character: '😕' },
            { title: 'face 39', character: '🙁' },
            { title: 'face 40', character: '☹️' },
            { title: 'face 41', character: '😣' },
            { title: 'face 42', character: '😖' },
            { title: 'face 43', character: '😫' },
            { title: 'face 44', character: '😩' },
            { title: 'face 45', character: '🥺' },
            { title: 'face 46', character: '😢' },
            { title: 'face 47', character: '😭' },
            { title: 'face 48', character: '😤' },
            { title: 'face 49', character: '😠' },
            { title: 'face 50', character: '😡' },
            { title: 'face 51 ', character: '🤬' },
            { title: 'face 52', character: '🤯' },
            { title: 'face 53', character: '😳' },
            { title: 'face 54', character: '🥵' },
            { title: 'face 55', character: '🥶' },
            { title: 'face 56', character: '😱' },
            { title: 'face 57', character: '😨' },
            { title: 'face 58', character: '😰' },
            { title: 'rocket', character: '🚀' },
            { title: 'wind blowing face', character: '🌬️' },
            { title: 'floppy disk', character: '💾' },
            { title: 'heart', character: '❤️' }
        ] );
}
